(live-add-pack-lib "deft")
(custom-set-variables '(deft-auto-save-interval 5))
(setq deft-extension "org")
(setq deft-text-mode 'org-mode)
(setq deft-directory "~/Dropbox/Notes")
(setq deft-use-filename-as-title t)
(require 'deft)
